version: "3.1" # secrets can't be used 2nd version

services:
  drupal:
    image: drupal:8.2
    ports:
      - "8080:80"
    volumes:
      - /path/on/host/modules:/var/www/html/modules 
      - /path/on/host/profiles:/var/www/html/profiles
      - /path/on/host/sites:/var/www/html/sites
      - /path/on/host/themes:/var/www/html/themes

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql-pw
    secrets: 
      - psql-pw

volumes:
  drupal-modules: 
  drupal-profiles:
  drupal-sites:
  drupal-themes:

secrets:
  psql-pw:
    external: true